services:
  mysql:
    image: mysql:8.3.0
    container_name: django_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: sneakers_db
    ports:
      - "3316:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
